[[server]]
name = "bird"
description = "Oracle cloud ARM server"
tags = ["syncs"]
[server.config]
address = "https://100.112.62.127:8120"
region = "us-west-2"
enabled = true

[[repo]]
name = "komodo-syncs-bird"
description = "Monorepo for Komodo syncs"
tags = ["syncs"]
[repo.config]
server_id = "bird"
repo = "benkoppe/komodo-syncs"
git_account = "benkoppe"
on_pull.path = "."
on_pull.command = """
  chmod +x ./docker-sops.sh
  find . -name '*bird.env' -exec ./docker-sops.sh -i --decrypt {} +
"""

[[repo]]
name = "trak-backend-bird"
tags = ["syncs"]
[repo.config]
server_id = "bird"
repo = "benkoppe/bear-trak-backend"
git_account = "benkoppe"
