[[stack]]
name = "cloudflared-local"
deploy = true
[stack.config]
server_id = "Local"

auto_pull = true
auto_update = true
destroy_before_deploy = true

linked_repo = "komodo-syncs"
run_directory = "./stacks/cloudflared"

environment = "CLOUDFLARED_TOKEN=[[CLOUDFLARED_TOKEN]]"


[[stack]]
name = "quick test"
deploy = true
[stack.config]
server_id = "Local"

auto_pull = true
linked_repo = "komodo-syncs"
run_directory = "./stacks/test"

environment = "CLOUDFLARED_TOKEN=[[CLOUDFLARED_TOKEN]]"
