services:
  calibre-web:
    image: lscr.io/linuxserver/calibre-web:latest
    container_name: calibre-web
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
      - DOCKER_MODS=linuxserver/mods:universal-calibre #optional
      - OAUTHLIB_RELAX_TOKEN_SCOPE=1 #optional
    volumes:
      - "/var/lib/komodo/stacks/calibre/web/data:/config"
      - "/var/lib/komodo/stacks/calibre/config/Calibre Library:/books"
    restart: unless-stopped
    networks:
      - cloudflared
  # calibre:
  #   image: lscr.io/linuxserver/calibre:latest
  #   container_name: calibre
  #   security_opt:
  #     - seccomp:unconfined #optional
  #   environment:
  #     - PUID=1000
  #     - PGID=1000
  #     - TZ=America/Los_Angeles
  #     - PASSWORD=twisted-epic-expletive-islamist-syrup #optional
  #     # - CLI_ARGS= #optional
  #   volumes:
  #     - /etc/komodo/stacks/calibre/config:/config
  #   # ports:
  #   #   - 8080:8080
  #   #   - 8181:8181
  #   #   - 8081:8081
  #   restart: unless-stopped
  #   networks:
  #     - cloudflared

networks:
  cloudflared:
    external: true # (CALIBRE) ports 8080, 8181, 8081 ; (CALIBRE-WEB) port 8083

