services:
  console:
    image: ghcr.io/georgmangold/console
    environment:
      - CONSOLE_MINIO_SERVER=https://minio.thekoppe.com
      - CONSOLE_MINIO_REGION=us-east-1
    restart: unless-stopped
    networks:
      - newt

networks:
  newt:
    external: true # port 9090
