services:
  nexterm:
    image: germannewsmaker/nexterm:latest
    container_name: nexterm
    restart: always
    volumes:
      - "/var/lib/komodo/stacks/nexterm/data:/app/data"
    env_file:
      - local.env
    network_mode: host
