services:
  bear-trak-go:
    extends:
      file: /var/lib/komodo/repos/trak-backend-bird/go-server/compose.yaml
      service: go-server
    container_name: bear-trak-go
    networks:
      - cloudflared
      - default
    env_file:
      - .env
      - bird.env
  db:
    extends:
      file: /var/lib/komodo/repos/trak-backend-bird/go-server/compose.yaml
      service: db
    volumes:
      - ./db-data:/var/lib/postgresql/data

networks:
  cloudflared:
    external: true
