[[stack]]
name = "bear-trak-go"
tags = ["syncs"]
deploy = true
[stack.config]
server_id = "bird"

auto_pull = true
auto_update = true
destroy_before_deploy = true

linked_repo = "komodo-syncs-bird"
run_directory = "./stacks/bird/beartrak/bear-trak-go"

run_directory = "go-server"
environment = """
  SCHOOL_CODE=cornell
  OPENROUTER_MODEL=deepseek/deepseek-chat-v3-0324:free
  SOURCE_COMMIT=main-linux-arm64
"""
additional_env_files = ["bird.env"]
