[[stack]]
name = "opengist"
deploy = true
tags = ["syncs"]
[stack.config]
server_id = "Local"

auto_pull = true
auto_update = true
destroy_before_deploy = true

linked_repo = "komodo-syncs"
reclone = true
run_directory = "./stacks/local/opengist"

environment = """
  OG_URL=https://gist.thekoppe.com

  OG_OIDC_PROVIDER_NAME=PocketID
  OG_OIDC_DISCOVERY_URL=https://pocket.thekoppe.com/.well-known/openid-configuration
  OG_OIDC_GROUP_CLAIM_NAME=groups
  OG_OIDC_ADMIN_GROUP=opengist-admin
"""
